{
 "title": "House Price Metrics",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Total Predictions over time",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "targets": [
    { "expr": "prediction_distribution_count", "legendFormat": "Total Predictions" }
   ]
  },
  { "title": "Prediction Distribution", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Predictions Over Time by Distribution Bucket",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "targets": [
    { "expr": "prediction_distribution_bucket", "legendFormat": "House price up to: {{le}}" }
   ]
  },
  {
   "title": "Prediction distribution",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "prediction_distribution_bucket", "legendFormat": "House price up to: {{le}}" }
   ]
  },
  { "title": "Missing Params", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Missing Parameters",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "missing_params_count_total", "legendFormat": "Missing Params Total" }
   ]
  },
  {
   "title": "Missing Params over Time",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "sum(missing_params_count_total)",
     "legendFormat": "Rate of Missing Params"
    }
   ]
  }
 ]
}