name: Continuous Testing

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        cd house_price_api
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: |
        cd house_price_api
        pytest

    - name: Docker Compose up test
      run: |
        docker-compose up --build --abort-on-container-exit --exit-code-from prometheus
        docker-compose down
